name: Setup vhskeelz-db
description: Setup vhskeelz-db, should run on ubuntu-22.04 runner
inputs:
  selenium:
    description: Support running Selenium scripts
    default: "false"
  service_account_b64:
    description: Base64 encoded service account JSON to login to Google
    required: true
runs:
  using: composite
  steps:
    - name: install poetry
      shell: bash
      run: pipx install poetry
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - name: install xvfb and chromedriver
      if: inputs.selenium == 'true'
      shell: bash
      run: |
        sudo apt-get update &&\
        sudo apt-get install -y xvfb &&\
        GOOGLEJSON="$(curl https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json)" &&\
        CHROME_URL="$(echo "${GOOGLEJSON}" | jq -r '.channels.Stable.downloads.chrome[] | select(.platform == "linux64") | .url')" &&\
        CHROMEDRIVER_URL="$(echo "${GOOGLEJSON}" | jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url')" &&\
        wget -O chrome.zip "${CHROME_URL}" &&\
        wget -O chromedriver.zip "${CHROMEDRIVER_URL}" &&\
        unzip chrome.zip &&\
        sudo chown -R root:root chrome-linux64 &&\
        sudo chmod +x chrome-linux64/chrome &&\
        sudo ln -s `pwd`/chrome-linux64/chrome /usr/bin/chrome &&\
        sudo ln -s `pwd`/chrome-linux64/chrome /usr/bin/google-chrome &&\
        unzip chromedriver.zip &&\
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/ &&\
        sudo chown root:root /usr/local/bin/chromedriver &&\
        sudo chmod +x /usr/local/bin/chromedriver
    - name: login to google and get secrets
      shell: bash
      run: |
        echo "${{ inputs.service_account_b64 }}" | base64 -d > service_account.json &&\
        gcloud auth activate-service-account --key-file=service_account.json &&\
        bin/env_secret_restore.sh
    - name: install python module and dependencies
      shell: bash
      run: poetry install
    - name: prevent github from disabling the scheduled workflow due to inactivity
      if: always()
      uses: OriHoch/keepalive-workflow@master
