name: Clear processing record
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 4'
jobs:
  clear_processing_record:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup vhskeelz-db
        uses: ./.github/actions/setup-vhskeelz-db
        with:
          selenium: "false"
          service_account_b64: ${{ secrets.SERVICE_ACCOUNT_B64 }}
      - run: poetry run vhskeelz-db processing-record-clear
