on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  db_update:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - env:
          SERVICE_ACCOUNT_B64: ${{ secrets.SERVICE_ACCOUNT_B64 }}
          PROCESSING_RECORD_ENABLED: "true"
          PROCESSING_RECORD_NAME: github_db_update
          PROCESSING_RECORD_ID: ${{ github.run_id }}
          VHSKEELZ_DB_ARGS: "load-data --extract"
        run: bin/ci_run.sh
