name: DB update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'
    - cron: '0 22 * * *'
    - cron: '0 21 * * *'
    - cron: '0 20 * * *'
    - cron: '0 19 * * *'
jobs:
  db_update:
    concurrency:
      group: db-update
    runs-on: ubuntu-22.04
    env:
      PROCESSING_RECORD_ENABLED: "true"
      PROCESSING_RECORD_ID: ${{ github.run_id }}
      SERVICE_ACCOUNT_FILE: service_account.json
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup vhskeelz-db
        uses: ./.github/actions/setup-vhskeelz-db
        with:
          selenium: "false"
          service_account_b64: ${{ secrets.SERVICE_ACCOUNT_B64 }}
      - name: run load_data
        env:
          PROCESSING_RECORD_NAME: ${{ github.event_name }}-github_db_update-load-data
        run: poetry run vhskeelz-db load-data --extract
      - name: run update-smoove-candidates-mailing-list
        env:
          PROCESSING_RECORD_NAME: ${{ github.event_name }}-github_db_update-update-smoove-candidates-mailing-list
        run: poetry run vhskeelz-db update-smoove-candidates-mailing-list
