on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  db_update:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - env:
          SERVICE_ACCOUNT_B64: ${{ secrets.SERVICE_ACCOUNT_B64 }}
        run: |
          echo "${SERVICE_ACCOUNT_B64}" | base64 -d > service_account.json &&\
          gcloud auth activate-service-account --key-file=service_account.json &&\
          bin/env_secret_restore.sh &&\
          export SERVICE_ACCOUNT_FILE=service_account.json &&\
          poetry install &&\
          poetry run vhskeelz-db load-data --extract
