name: DB update Skeelz Export
on:
  workflow_dispatch:
  schedule:
    # Daily 00:22 (UTC) == 03:22 (Israel)
    - cron: '0 22 * * *'
env:
  PROCESSING_RECORD_ENABLED: "true"
  PROCESSING_RECORD_ID: ${{ github.run_id }}
  SERVICE_ACCOUNT_FILE: service_account.json
jobs:
  db_update_skeelz_export:
    concurrency:
      group: db-update-skeelz-export
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup vhskeelz-db
        uses: ./.github/actions/setup-vhskeelz-db
        with:
          selenium: "true"
          service_account_b64: ${{ secrets.SERVICE_ACCOUNT_B64 }}
      - name: run load_data
        env:
          PROCESSING_RECORD_NAME: ${{ github.event_name }}-github_db_update-skeelz-export
        run: xvfb-run poetry run vhskeelz-db load-data --extract --only-table-types skeelz_export
