name: Scheduled mailing - new_matches
on:
  workflow_dispatch:
  schedule:
    # Every Thursday at 01:43 (UTC)
    - cron: '43 1 * * 4'
jobs:
  scheduled_mailing_new_matches:
    concurrency:
      group: mailing-new_matches
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: send mailing
        uses: ./.github/actions/send-candidate-offers-mailing
        with:
          run_args: "--test-email-to=default --test-email-update-db"
          no_dry_run: "DANGER"
          mailing_type: "new_matches"
          service_account_b64: ${{ secrets.SERVICE_ACCOUNT_B64 }}
          processing_record_name: "schedule-send-candidate-offers-mailing-new_matches"
          processing_record_id: ${{ github.run_id }}
