name: Scheduled mailing - new_matches
on:
  workflow_dispatch:
#  schedule:
    # Every day at 14:03 (UTC) == 17:03 (Israel)
#    - cron: '3 14 * * *'
jobs:
  scheduled_mailing_new_matches:
    runs-on: ubuntu-22.04
    concurrency:
      group: mailing_new_matches
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: send mailing
        uses: ./.github/actions/send-candidate-offers-mailing
        with:
          run_args: "--allow-send"
          no_dry_run: "DANGER"
          mailing_type: "new_matches"
          service_account_b64: ${{ secrets.SERVICE_ACCOUNT_B64 }}
          processing_record_name: "schedule-send-candidate-offers-mailing-new_matches"
          processing_record_id: ${{ github.run_id }}
