name: Scheduled mailing - new_position
on:
  workflow_dispatch:
  schedule:
    # Every day at 05:52 (UTC) == 08:52 (Israel)
    - cron: '52 5 * * *'
jobs:
  scheduled_mailing_new_position:
    concurrency:
      group: mailing-new_position
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: send mailing
        uses: ./.github/actions/send-candidate-offers-mailing
        with:
          run_args: "--test-email-to=default --test-email-update-db"
          no_dry_run: "DANGER"
          mailing_type: "new_position"
          service_account_b64: ${{ secrets.SERVICE_ACCOUNT_B64 }}
          processing_record_name: "schedule-send-candidate-offers-mailing-new_position"
          processing_record_id: ${{ github.run_id }}
