on:
  workflow_dispatch:
jobs:
  send_candidate_offers_mailings:
    strategy:
      matrix:
        mailing_type:
          - num_fits
          - interested
          - new_matches
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - env:
          SERVICE_ACCOUNT_B64: ${{ secrets.SERVICE_ACCOUNT_B64 }}
          PROCESSING_RECORD_ENABLED: "true"
          PROCESSING_RECORD_NAME: github_db_update
          PROCESSING_RECORD_ID: ${{ github.run_id }}
        run: |
          sudo apt-get update &&\
          sudo apt-get install -y xvfb &&\
          CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE` &&\
          wget https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip &&\
          unzip chromedriver_linux64.zip &&\
          sudo mv chromedriver /usr/local/bin/ &&\
          sudo chown root:root /usr/local/bin/chromedriver &&\
          sudo chmod +x /usr/local/bin/chromedriver &&\
          echo "${SERVICE_ACCOUNT_B64}" | base64 -d > service_account.json &&\
          gcloud auth activate-service-account --key-file=service_account.json &&\
          bin/env_secret_restore.sh &&\
          export SERVICE_ACCOUNT_FILE=service_account.json &&\
          poetry install &&\
          xvfb-run poetry run vhskeelz-db send-candidate-offers-mailing ${{ matrix.mailing_type }} --dry-run
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.mailing_type }}
          path: .data
